config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-beige-crocodile.sh
        container: qc.acc_gimpy-maroon-otter
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cornflower-macaw.sh
        container: qc.doc_beady-champagne-shrimp
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-green-millipede.sh
        container: qc.doc_crabby-chocolate-olm
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-smalt-malamute.sh
        container: qc.doc_snoopy-pear-barracuda
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ultramarine-whippet.sh
        container: qc.lic_snazzy-buff-fish
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-gamboge-capybara.sh
        container: qc.met_lumpy-firebrick-butterfly
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-tomato-echidna.sh
        container: qc.met_crappy-jade-angelfish
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-frontend bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-burgundy-hare.sh
        container: qc.sec_homey-coral-opossum
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-jade-dodo.sh
        container: qc.sty_flimsy-viridian-coyote
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-scarlet-rat.sh
        container: qc.sty_craggy-wisteria-bear
      github.com/WORSICA/eosc-worsica-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cobalt-bulldog.sh
        container: qc.sty_jumpy-taupe-okapi
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ecru-chinchilla.sh
        container: qc.ver_tacky-cobalt-burmese
timeout: 1800
