config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-aquamarine-ray.sh
        container: qc.acc_snappy-champagne-chicken
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-myrtle-catfish.sh
        container: qc.doc_gamy-auburn-walrus
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ruby-zebra.sh
        container: qc.doc_gloppy-mauve-dhole
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-silver-argentino.sh
        container: qc.doc_chewy-magenta-flounder
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-wheat-emu.sh
        container: qc.lic_freaky-gold-kiwi
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-grey-capuchin.sh
        container: qc.met_bumpy-aqua-millipede
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-silver-kingfisher.sh
        container: qc.met_dorky-ultramarine-malamute
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-frontend bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-mauve-panda.sh
        container: qc.sec_lovely-bistre-shrimp
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-salmon-robin.sh
        container: qc.sty_stealthy-eggplant-guppy
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amber-scorpion.sh
        container: qc.sty_leaky-harlequin-okapi
      github.com/WORSICA/eosc-worsica-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-peach-cheetah.sh
        container: qc.sty_skanky-maroon-chihuahua
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-pumpkin-tortoise.sh
        container: qc.ver_grumpy-bronze-nightingale
timeout: 1800
