config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-rose-magpie.sh
        container: qc.acc_chummy-periwinkle-hedgehog
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-alizarin-cassowary.sh
        container: qc.doc_goopy-violet-numbat
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-sapphire-panda.sh
        container: qc.doc_cozy-fuchsia-affenpinscher
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-tan-jellyfish.sh
        container: qc.doc_whiny-indigo-dormouse
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-bistre-buffalo.sh
        container: qc.lic_scanty-taupe-mandrill
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-asparagus-schnauzer.sh
        container: qc.met_blurry-flax-hare
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-corn-jellyfish.sh
        container: qc.met_shaky-heliotrope-slug
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pumpkin-stingray.sh
        container: qc.sty_chummy-asparagus-oriole
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-magenta-ray.sh
        container: qc.ver_trippy-beige-hyrax
timeout: 1800
