config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magenta-frigatebird.sh
        container: qc.acc_sloppy-linen-skunk
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-crimson-barnacle.sh
        container: qc.doc_hilly-burgundy-kiwi
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rose-moorhen.sh
        container: qc.doc_chewy-yellow-hamster
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-tangerine-spider.sh
        container: qc.doc_scummy-dandelion-mule
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-rose-cat.sh
        container: qc.lic_sickly-sangria-millipede
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cornflower-rottweiler.sh
        container: qc.met_fuzzy-cream-hyrax
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-celadon-turkey.sh
        container: qc.met_tasty-brass-bonobo
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-frontend bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cyan-turkey.sh
        container: qc.sec_surly-grey-mist
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-magenta-cuttlefish.sh
        container: qc.sty_sunny-cinnabar-dachsbracke
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-sapphire-beetle.sh
        container: qc.sty_stealthy-grey-robin
      github.com/WORSICA/eosc-worsica-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-apricot-sheepdog.sh
        container: qc.sty_baggy-brown-llama
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-amaranth-toucan.sh
        container: qc.ver_sleepy-amaranth-owl
timeout: 1800
