config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-orchid-badger.sh
        container: qc.acc_hilly-puce-affenpinscher
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-lime-zebu.sh
        container: qc.doc_freaky-maroon-tarantula
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-auburn-eel.sh
        container: qc.doc_cozy-saffron-frigatebird
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cream-lizard.sh
        container: qc.doc_shabby-black-bee
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lemon-ostrich.sh
        container: qc.lic_thirsty-maroon-saola
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-champagne-caterpillar.sh
        container: qc.met_smelly-myrtle-wolverine
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-chartreuse-chinchilla.sh
        container: qc.met_homey-mauve-cougar
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-frontend bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cinnamon-deer.sh
        container: qc.sec_bumpy-aquamarine-loon
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-cream-heron.sh
        container: qc.sty_stuffy-russet-fox
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-thistle-newt.sh
        container: qc.sty_jumpy-brass-cow
      github.com/WORSICA/eosc-worsica-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ruby-crab.sh
        container: qc.sty_shabby-pumpkin-mau
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-firebrick-nightingale.sh
        container: qc.ver_woolly-beige-toucan
timeout: 1800
