config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-rose-hyena.sh
        container: qc.acc_boozy-razzmatazz-bird
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-mauve-mouse.sh
        container: qc.doc_cloudy-silver-sloth
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-sangria-beetle.sh
        container: qc.doc_fuzzy-apricot-mastiff
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-apricot-drever.sh
        container: qc.doc_cloudy-apricot-elephant
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-pumpkin-moth.sh
        container: qc.lic_pasty-gamboge-jackal
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-viridian-budgerigar.sh
        container: qc.met_squeaky-cerise-mouse
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-pumpkin-shrew.sh
        container: qc.met_pasty-gamboge-gibbon
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-razzmatazz-emu.sh
        container: qc.sty_smelly-pumpkin-flamingo
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-harlequin-akita.sh
        container: qc.ver_snoopy-emerald-tiger
timeout: 1800
