config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-magnolia-seal.sh
        container: qc.acc_muggy-wheat-lionfish
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sapphire-numbat.sh
        container: qc.doc_smelly-white-manatee
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-peach-tortoise.sh
        container: qc.doc_woozy-wisteria-rottweiler
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-linen-eel.sh
        container: qc.doc_pretty-silver-chicken
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-smalt-lynx.sh
        container: qc.lic_bumpy-emerald-cow
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-asparagus-avocet.sh
        container: qc.met_wimpy-mauve-slug
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tangerine-hummingbird.sh
        container: qc.met_tasty-rust-toad
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-frontend bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-ruby-coati.sh
        container: qc.sec_baggy-turquoise-crocodile
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-puce-russel.sh
        container: qc.sty_woolly-flax-crab
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-peach-armadillo.sh
        container: qc.sty_freaky-champagne-labradoodle
      github.com/WORSICA/eosc-worsica-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-violet-buffalo.sh
        container: qc.sty_grumpy-thistle-whippet
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cream-birman.sh
        container: qc.ver_slaphappy-plum-bongo
timeout: 1800
