config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-frontend:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-frontend
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-silver-monkey.sh
        container: qc.acc_snippy-violet-worm
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-frontend find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-crimson-oyster.sh
        container: qc.doc_bumpy-chartreuse-chow
      github.com/WORSICA/eosc-worsica-frontend git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-grey-hyena.sh
        container: qc.doc_leaky-brass-chameleon
      github.com/WORSICA/eosc-worsica-frontend markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-teal-tang.sh
        container: qc.doc_gummy-green-argentino
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-frontend licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-viridian-manatee.sh
        container: qc.lic_flaky-scarlet-magpie
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-frontend cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-jade-cuscus.sh
        container: qc.met_chewy-zucchini-badger
      github.com/WORSICA/eosc-worsica-frontend validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-silver-vulture.sh
        container: qc.met_jumpy-thistle-weasel
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-frontend bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-smalt-koala.sh
        container: qc.sec_seedy-linen-ibis
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-frontend flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cobalt-gorilla.sh
        container: qc.sty_lanky-harlequin-duck
      github.com/WORSICA/eosc-worsica-frontend jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cobalt-binturong.sh
        container: qc.sty_skimpy-lime-jackal
      github.com/WORSICA/eosc-worsica-frontend stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-olive-chinook.sh
        container: qc.sty_flimsy-burgundy-kudu
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-frontend get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sangria-chinook.sh
        container: qc.ver_messy-razzmatazz-tiger
timeout: 1800
